export const poems = [
    { date: '2025-02-14', content: 'Je suis parti il y a quelques heures,\nflottant sans bruit au creux des nuages.\nSous mes yeux, le monde s’efface,\net je rêve de nous, légers comme l’air,\nsurvolant l’infini.\n\nJe nous vois danser, portés par le vent,\neffleurant l’éclat des cieux.\nLà-haut, où le soleil s’endort en feu,\nnous serions libres, suspendus au temps,\nà chaque battement d’aile partagé.' },
    { date: '2025-02-15', content: 'J’atterris dans quelques heures, probablement,\nLes rêves en cascade au creux de la tête,\nEt mon cœur, débordant d’un amour pour toi,\nComme un feu doux qui ne s’éteint jamais.' },
    { date: '2025-02-16', content: '' },
    { date: '2025-02-17', content: 'Poème 4 : Un souffle de vie.' },
    { date: '2025-02-18', content: 'Poème 5 : L\'éveil des sens.' },
    { date: '2025-02-19', content: 'Poème 6 : Une douce mélodie.' },
    { date: '2025-02-20', content: 'Poème 7 : La beauté du monde.' },
    { date: '2025-02-21', content: 'Poème 8 : Un rêve éveillé.' },
    { date: '2025-02-22', content: 'Poème 9 : La lumière de l\'aube.' },
    { date: '2025-02-23', content: 'Poème 10 : Un instant de paix.' },
    { date: '2025-02-24', content: 'Poème 11 : La douceur du soir.' },
    { date: '2025-02-25', content: 'Poème 12 : Un chant d\'amour.' },
    { date: '2025-02-26', content: 'Poème 13 : La magie des mots.' },
    { date: '2025-02-27', content: 'Poème 14 : Un éclat de rire.' },
    { date: '2025-02-28', content: 'Poème 15 : La beauté intérieure.' },
    { date: '2025-03-01', content: 'Poème 16 : La force de l\'âme.' },
    { date: '2025-03-02', content: 'Poème 17 : Un souffle d\'espoir.' },
    { date: '2025-03-03', content: 'Poème 18 : La douceur du matin.' },
    { date: '2025-03-04', content: 'Poème 19 : Un instant de bonheur.' },
    { date: '2025-03-05', content: 'Poème 20 : La beauté du silence.' },
    { date: '2025-03-06', content: 'Poème final : L\'apothéose.' },
]
