export const poems = [
    { date: '2025-02-14', content: 'Je suis parti il y a quelques heures,\nflottant sans bruit au creux des nuages.\nSous mes yeux, le monde s’efface,\net je rêve de nous, légers comme l’air,\nsurvolant l’infini.\n\nJe nous vois danser, portés par le vent,\neffleurant l’éclat des cieux.\nLà-haut, où le soleil s’endort en feu,\nnous serions libres, suspendus au temps,\nà chaque battement d’aile partagé.' },
    { date: '2025-02-15', content: 'J’atterris dans quelques heures, probablement,\nLes rêves en cascade au creux de la tête,\nEt mon cœur, débordant d’un amour pour toi,\nComme un feu doux qui ne s’éteint jamais.' },
    { date: '2025-02-16', content: 'Mon amour, le Japon est magique, mais rien ici ne peut rivaliser avec toi. Chaque pas que je fais me rappelle combien tu me manques.' },
    { date: '2025-02-17', content: 'Sur le chemin où danse la brume,\nChaque pas murmure ton nom en écho.\nMais ton rire, étoile qui s’allume,\nMe guide et réchauffe mon cœur en sursaut.\n\nMême loin, je ressens ta lumière,\nComme un doux serment au creux du matin.\nMon amour, tu es ma plus belle lumière,\nL’horizon où se perdent mes mains.' },
    { date: '2025-02-18', content: 'Je pense à toi à chaque instant, à ta douceur et à nos souvenirs.\n\nTu es ma plus belle aventure infini, même à des milliers de kilomètres.' },
    { date: '2025-02-19', content: 'Écoute cette rivière qui chante,\nSon murmure secret entre les pierres.\nDans ses notes, je dépose mes pensées,\nFlottant vers toi, libre et sincère.' },
    { date: '2025-02-20', content: 'Chaque jour loin de toi est un défi, mais je garde ton sourire en tête, et cela me donne la force d’avancer.' },
    { date: '2025-02-21', content: 'Les rêves m’ont mené au bord des cimes,\nOù le monde s’endort sous un ciel opalin.\nMais c’est ton regard, étoile ultime,\nQui éclaire mes nuits sans fin.' },
    { date: '2025-02-22', content: 'Je découvre des paysages incroyables, mais aucun ne rivalise avec la beauté de ton visage. Tu es ma maison.' },
    { date: '2025-02-23', content: 'Au cœur d’une clairière silencieuse,\nLe vent dépose un baiser discret.\nJe l’imagine voyager vers toi,\nDéposant mon amour en secret.' },
    { date: '2025-02-24', content: 'Même au bout du monde, tu es mon point de repère. Je compte les jours avant de te revoir.' },
    { date: '2025-02-25', content: 'Chante encore cette mélodie,\nCelle que les étoiles écoutent en silence.\nTes mots, doux échos infinis,\nDansent en moi avec élégance.' },
    { date: '2025-02-26', content: 'Ton amour est mon talisman, ma lumière dans ce voyage. Tu es dans chaque pensée, dans chaque paysage.' },
    { date: '2025-02-27', content: 'Le rire éclate comme un feu de joie,\nSous la voûte étoilée d’un soir complice.\nAvec toi, même l’éternité ploie,\nCar chaque instant devient délice.' },
    { date: '2025-02-28', content: 'Je me promène dans des temples sacrés, mais mon plus grand sanctuaire reste ton cœur. Merci d’être celle que j’aime.' },
    { date: '2025-03-01', content: 'Dans la tempête et ses tourments,\nJe trouve refuge entre tes bras.\nTon amour est l’ancre des éléments,\nEt ma boussole ne tremble pas.' },
    { date: '2025-03-02', content: 'Quand la brume s’étire sur l’horizon,\nJ’entends le souffle léger de l’espoir.\nTon sourire trace une nouvelle saison,\nOù chaque aurore est une victoire.' },
    { date: '2025-03-03', content: 'Aujourd’hui est un jour particulier, mon anniversaire.\nHabituellement, je le fête seul, entouré de réflexions et de souvenirs. Mais aujourd’hui, plus que jamais, j’aurais aimé t’avoir à mes côtés.\n\nChaque instant passé loin de toi me rappelle à quel point tu es devenue essentielle dans ma vie. Ce n’est pas seulement une question de présence physique, mais une envie profonde de te voir partager ces moments, grands ou petits.\n\nJe ressens une immense hâte de te revoir, de te serrer contre moi, de te raconter ce que j’ai vu et vécu ici. Pourtant, rien de ce que je vis au Japon ne peut égaler ce que je ressens quand je suis avec toi.\n\nAujourd’hui, plus que tout, je me rends compte de l’importance de construire avec toi quelque chose de sincère, de durable, et de beau. Un lien qui transcende les distances et les épreuves.\n\nMerci d’être celle qui, même de loin, fait battre mon cœur plus fort. Je t’aime.' },
    { date: '2025-03-04', content: 'Poème 19 : Un instant de bonheur.' },
    { date: '2025-03-05', content: 'Poème 20 : La beauté du silence.' },
    { date: '2025-03-06', content: 'Poème final : L\'apothéose.' },
]
