export const poems = [
    { date: '2026-07-25', content: 'Laisse le temps faire son travail.\nMoi je suis là, sans horloge,\nsans liste, sans attente cachée\nqui te tomberait dessus un jour.\n\nOn verra bien ce que ça donne.\nEt ce que ça donne, ça me va.' },
    { date: '2026-07-26', content: 'Avec toi, tout semble possible.' },
    { date: '2026-07-27', content: 'Ton sourire est ma plus grande joie.' },
    { date: '2026-07-28', content: 'Tu es mon refuge, ma lumière.' },
    { date: '2026-07-29', content: 'Dans chaque instant, je trouve ta présence.' },
    { date: '2026-07-30', content: 'Le Sentiment Flou\n\nUn amour sans nom, un feu sans visage,\nQui brille la nuit au fond de mes pas.\nEst-ce un doux vent, est-ce un vain mirage,\nUn lien si fort qu\'on ne nomme pas ?\n\nJe ne sais rien de cette douce emprise,\nQui tremble et rit au bord de mes yeux.\nC\'est un secret que le vent déguise,\nUn peu de terre et beaucoup de cieux.\nNi tout à fait l\'ami, ni tout l\'autre,\nJuste un écho qui berce mon sort.\nUn doux mystère qui devient nôtre,\nUn fil incertain qui rend plus fort.' },
    { date: '2026-07-31', content: 'Tu poses les mots,\ncomme on pose une main sur une épaule :\nsans appuyer, sans réclamer,\njuste assez pour qu\'on sache\nque quelqu\'un est là.\nIl y a des gens qui parlent pour occuper l\'espace.\nToi tu parles pour le rendre habitable.' },
    { date: '2026-08-01', content: 'Quand tu écoutes,\nle monde ralentit d\'un cran.\nLes phrases ont le temps de finir,\nles silences ne sont plus gênants,\net on s\'entend penser.\nC\'est rare, quelqu\'un qui écoute vraiment.\nOn repart de ces moments-là\nen respirant mieux qu\'en arrivant.' },
    { date: '2026-08-02', content: 'Belle, intelligente et attentionnée.\nÀ toi, je veux dire ce que je pense,\nje veux te dire que tu es importante.' },
    { date: '2026-08-03', content: 'Dans ta mémoire immortelle,\nComme dans le reposoir\nD\'une divine chapelle,\nPour celui qui t\'est fidèle,\nGarde l\'amour et l\'espoir.\n\nGarde l\'amour qui m\'enivre,\nL\'amour qui nous fait rêver ;\nGarde l\'espoir qui fait vivre ;\nGarde la foi qui délivre,\nLa foi qui nous doit sauver.\n\nL\'espoir, c\'est de la lumière,\nL\'amour, c\'est une liqueur,\nEt la foi, c\'est la prière.\nMets ces trésors, ma très chère,\nAu plus profond de ton coeur.\n\nNérée Beauchemin.' },
    { date: '2026-08-04', content: '' },
    { date: '2026-08-05', content: '' },
    { date: '2026-08-06', content: '' },
    { date: '2026-08-07', content: '' },
    { date: '2026-08-08', content: '' },
    { date: '2026-08-09', content: '' },
    { date: '2026-08-10', content: '' },
    { date: '2026-08-11', content: '' },
    { date: '2026-08-12', content: '' },
    { date: '2026-08-13', content: '' },
]
